export const verificationItems = [
  {
    id: 'registration_card',
    type: 'Photo',
    title: 'Registration Card',
    description: '',
    steps: ['Please take a photo from the center position of the left side (driver) of your vehicle capturing the entire exterior left side of your vehicle'],
    image: '/images/Photo1Exterior Left.png',
    video: '/images/Clip 1 - Front.mov',
    loading: false,
  },
  {
    id: 'Odometer',
    type: 'Photo',
    title: 'odometer',
    description: '',
    steps: ['Please take a photo from the center position of the right side (Passenger) of your vehicle capturing the entire exterior right side of your vehicle'],
    image: '/images/Photo2Exterior Right.png',
    video: '/images/Clip 2 - Rear.mov',
    loading: false,
  },
];

export const interiorItems = [
  {
    id: 'horn',
    type: 'Video',
    title: 'Horn',
    description: '',
    steps: ['Please take a photo from the center position of the left side (driver) of your vehicle capturing the entire exterior left side of your vehicle'],
    image: '/images/Photo1Exterior Left.png',
    video: '/images/Clip 1 - Front.mov',
    loading: false,
  },
  {
    id: 'interior_driverside',
    type: 'Photo',
    title: 'Interior Driverside',
    description: '',
    steps: ['Please take a photo from the center position of the right side (Passenger) of your vehicle capturing the entire exterior right side of your vehicle'],
    image: '/images/Photo2Exterior Right.png',
    video: '/images/Clip 2 - Rear.mov',
    loading: false,
  },
  {
    id: 'driver_seat_adjusted',
    type: 'Clip',
    title: 'Driver seat Adjusted',

    description: 'Instructional video on how to record video of rear of moving vehicle',
    steps: [
      'Please record a short video clip showing the front of the vehicle with all the front lights, indicators and windshield wipers turned on. Our goal is to verify the functionality of those features and identify any major damage on the front',
    ],
    video: '/images/Clip 1 - Front-1-720p.m4v',
    loading: false,
  },
  {
    id: 'interior_passengerside',
    type: 'Clip',
    title: 'Interior Passengerside',
    description: "Instructional video on how to record your vehicle's exterior",
    steps: [
      'Set phone down behind car (or have someone hold the phone with car in field of view); once camera is positioned well, drive car 3-5 feet in reverse and push on the brake pedal. Once car is in the park mode, push the gas pedal. Please ensure that the sound is clear(for checking muffler and for brake sound) and the brake light is in the clear view',
    ],
    video: '/images/Clip 2 - Rear-1-720p.m4v',
    loading: false,
  },
  {
    id: 'passenger_seat_adjusted',
    type: 'Photo',
    title: 'Passenger seat Adjusted',
    description: '',
    steps: ['Please take a photo of the interior of the vehicle with left driver side door open with clear view of the interior rearview mirror and brakepads. '],
    image: '/images/Photo 3 - Driverside Interior.png',
    loading: false,
  },
  {
    id: 'interior_backseat',
    type: 'Photo',
    title: 'Interior Backseat',
    description: '',
    steps: ['Please take a photo entire odometer dashboard area with vehicle turned on.'],
    image: '/images/Photo 5Odometer.png',
    loading: false,
  },
];

export const exteriorItems = [
  {
    id: 'exterior_left',
    type: 'Photo',
    title: 'Exterior left',
    description: '',
    steps: ['Please take a photo of the interior of the vehicle with left driver side door open with clear view of the interior rearview mirror and brakepads. '],
    image: '/images/Photo 3 - Driverside Interior.png',
    loading: false,
  },
  {
    id: 'exterior_right',
    type: 'Photo',
    title: 'Exterior Right',
    description: '',
    steps: ['Please take a photo entire odometer dashboard area with vehicle turned on.'],
    image: '/images/Photo 5Odometer.png',
    loading: false,
  },
  {
    id: 'exterior_front',
    type: 'Video',
    title: 'Exterior Front',
    description: '',
    steps: ['Please take a photo of the interior of the vehicle with right passenger side door open with clear view of the inside. '],
    image: '/images/Photo4Passengerside Interior.png',
    loading: false,
  },
  {
    id: 'exterior_rear',
    type: 'Video',
    title: 'Exterior Rear',
    description: '',
    steps: ['Please take a photo of the backseats with back doors opened and seatbelts buckled.'],
    image: '/images/Photo6Backseat.png',
    loading: false,
  },
];

export const tires = [
  {
    id: 'left_front_tire',
    type: 'Photo',
    title: 'Left Front Tire',
    description: '',
    steps: ['Please take a photo of the interior of the vehicle with left driver side door open with clear view of the interior rearview mirror and brakepads. '],
    image: '/images/Photo 3 - Driverside Interior.png',
    loading: false,
  },
  {
    id: 'left_rear_tire',
    type: 'Photo',
    title: 'Left Rear Tire',
    description: '',
    steps: ['Please take a photo entire odometer dashboard area with vehicle turned on.'],
    image: '/images/Photo 5Odometer.png',
    loading: false,
  },
  {
    id: 'right_front_tire',
    type: 'Photo',
    title: 'Right Front Tire',
    description: '',
    steps: ['Please take a photo entire odometer dashboard area with vehicle turned on.'],
    image: '/images/Photo 5Odometer.png',
    loading: false,
  },
  {
    id: 'right_rear_tire',
    type: 'Photo',
    title: 'Right Rear Tire',
    description: '',
    steps: ['Please take a photo entire odometer dashboard area with vehicle turned on.'],
    image: '/images/Photo 5Odometer.png',
    loading: false,
  },
];
